[Variables]
Color1=128,128,128,255
Color2=255,255,255,230
Color3=128,128,128,100
Color4=186,55,51,200
Color5=0,0,0,210
Color6=255,255,255,255
Color7=204,0,0,255
Color8=162,18,43,255
LocalFontFace=Code Light
LocalFontFace2=Code Bold
LocalFontFace3=ITC Avant Garde Pro Md

HDD1=X:
HDD2=D:
HDD3=E:

January=JAN
February=FEB
March=MAR
April=APR
May=MAY
June=JUN
July=JUL
August=AUG
September=SEP
October=OCT
November=NOV
December=DEC

Monday=MON
Tuesday=TUE
Wednesday=WED
Thursday=THU
Friday=FRi
Saturday=SAT
Sunday=SUN

