
;--GREY----------------

[lightr]
StringAlign=right
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,30
FontColor=#color1#
FontFace=#LocalFontFace#
AntiAlias=1
ClipString=0

[lightl]
StringAlign=left
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,30
FontColor=#color1#
FontFace=#LocalFontFace#
AntiAlias=1
ClipString=0

[boldr]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,30
FontColor=#color1#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[boldr2]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=255,255,255,40
FontColor=#color1#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[boldl2]
StringAlign=left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=255,255,255,40
FontColor=#color1#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[boldc]
StringAlign=center
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,80
FontColor=#color1#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[boldplayer]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=#color1#
FontFace=#LocalFontFace3#
AntiAlias=1
ClipString=1

[boldtime]
StringAlign=left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,100
FontColor=255,255,255,220
FontFace=#LocalFontFace3#
AntiAlias=1
ClipString=0

[playerbuttons]
StringAlign=center
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,20
FontColor=#color1#
FontFace=Webdings
FontSize=10
AntiAlias=1
ClipString=0



;--BLACK----------------

[blklightr]
StringAlign=right
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,30
FontColor=#color5#
FontFace=#LocalFontFace#
AntiAlias=1
ClipString=0

[blklightl]
StringAlign=left
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,30
FontColor=#color5#
FontFace=#LocalFontFace#
AntiAlias=1
ClipString=0

[blkboldr]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,40
FontColor=#color5#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[blkboldr2]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,80
FontColor=#color2#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[blkboldl]
StringAlign=left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,80
FontColor=#color5#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[blkboldl2]
StringAlign=left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,80
FontColor=#color2#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[blkboldplayer]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,100
FontColor=#color2#
FontFace=#LocalFontFace3#
AntiAlias=1
ClipString=1

[blkplayerbuttons]
StringAlign=center
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,80
FontColor=#color2#
FontFace=Webdings
FontSize=10
AntiAlias=1
ClipString=0



;--WHITE----------------

[whtlightr]
StringAlign=right
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,30
FontColor=#color6#
FontFace=#LocalFontFace#
AntiAlias=1
ClipString=0

[whtlightl]
StringAlign=left
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=#color6#
FontFace=#LocalFontFace#
AntiAlias=1
ClipString=0

[whtboldr]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,80
FontColor=#color6#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[whtboldr2]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,92
FontColor=#color6#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[whtboldl2]
StringAlign=left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,92
FontColor=#color6#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[whtboldc]
StringAlign=center
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,80
FontColor=#color6#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[whtboldplayer]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,100
FontColor=#color6#
FontFace=#LocalFontFace3#
AntiAlias=1
ClipString=1

[whtplayerbuttons]
StringAlign=center
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,80
FontColor=#color6#
FontFace=Webdings
FontSize=10
AntiAlias=1
ClipString=0



;--RED----------------

[redlightr]
StringAlign=right
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,40
FontColor=#color7#
FontFace=#LocalFontFace#
AntiAlias=1
ClipString=0

[redlightl]
StringAlign=left
StringCase=None
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,40
FontColor=#color7#
FontFace=#LocalFontFace#
AntiAlias=1
ClipString=0

[redboldr]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,40
FontColor=#color8#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[redboldr2]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,92
FontColor=#color7#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[redboldl2]
StringAlign=left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,92
FontColor=#color7#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[redboldc]
StringAlign=center
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,80
FontColor=#color7#
FontFace=#LocalFontFace2#
AntiAlias=1
ClipString=0

[redboldplayer]
StringAlign=right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,100
FontColor=#color7#
FontFace=#LocalFontFace3#
AntiAlias=1
ClipString=1

[redplayerbuttons]
StringAlign=center
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,80
FontColor=#color7#
FontFace=Webdings
FontSize=10
AntiAlias=1
ClipString=0
