; ----------------------
; Unless you know what you're doing, hover over the skin and
; click on the wrench that appears to change these settings easily.
; ----------------------

[Variables]
font.Name=Aller
text.Size=9
blur.Enable=1
color.Skin=1C71A466
color.Title=FFFFFFFF
color.Text=B5E3E2CC
color.Highlight=E98E2CFF
disks.1=C:
disks.2=D:
disks.3=E:
disks.4=F:
disks.5=G:
disks.6=H:
disks.7=I:
disks.8=J:
mediaplayer=AIMP
weather.Code=FIXX0002
weather.Unit=C
mail.User=sda2225
mail.Pass=!guswnd7606G
twitter.User=
twitter.Pass=
gcal.URL=https://mail.google.com/mail/u/0/?tab=cm#inbox
facebook.URL=https://www.facebook.com/xDeTK
feeds.URL1=http%3A%2F%2Fnews.google.com%2Fnews%3Fpz%3D1%26cf%3Dall%26ned%3Dus%26hl%3Den%26topic%3Dh%26num%3D3%26output%3Drss
feeds.URL2=http%3A%2F%2Fwww.xkcd.com%2Fatom.xml
feeds.URL3=http%3A%2F%2Ffeeds.gawker.com%2Fgizmodo%2Fexcerpts.xml
feeds.URL4=http%3A%2F%2Ffeeds.gawker.com%2Flifehacker%2Fexcerpts.xml
network.MaxUp=10485760
network.MaxDown=12582912
slideshow.Path=D:\ALL\세이버\사쿠라세이버
