[Variables]
;===== MAIN TEXT =====
MainText=255,255,255,0

;Y value for text, horizontal only, 텍스트의 Y 값, 가로 전용
TextY=0
;X value for text, vertical only, 텍스트의 X 값 (세로)
TextX=0

;===== INDICATOR OPTIONS =====
CurrentText=255,255,255,255

;Box Options ,왼쪽 간격
IndicatorWidth=30
IndicatorHeight=0
IndicatorColorTop=0,0,0,100
IndicatorColorBot=0,0,0,100

;Box Shape ,상단 간격
;HORIZONTAL- Set to 1 to display both top and bottom rounded portions, 2 to show only the top, and 3 to show only the bottom.
;VERTICAL- Set to 1 to display both left and right rounded portions, 2 to show only the left, and 3 to show only the right.
;Indicator=0

;===== GENERAL OPTIONS =====
;Set to 1 to dynamically center on the screen. Note that this moves the whole skin.
Center=1

;Background Color, 배경 색깔
BgColor=0,0,0,0
;Total Skin Width-Horizontal Version, 총 스킨 폭 - 수평 버전
SWidth=#SCREENAREAWIDTH# / 100
;Total Skin Height-Vertical Version, 총 스킨 폭 - 세로 버전
SHeight=#SCREENAREAHEIGHT#
;Set to one to hide week indicators, 주 지표를 숨기려면 1로 설정하십시오.
WIndic=1
