[MeasureFFT_L_00]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=1
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_01]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=1
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_02]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=2
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_03]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=3
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_04]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=4
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_05]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=5
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_06]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=6
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_07]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=7
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_08]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=8
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_09]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=9
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=10
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=11
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=12
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=13
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=14
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=15
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=16
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=17
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=18
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=19
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=20
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=21
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=22
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=23
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_24]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=24
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_25]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=25
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_26]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=26
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_27]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=27
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_28]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=28
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_29]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=29
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_30]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=30
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_31]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=31
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_32]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=32
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_33]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=33
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_34]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=34
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_35]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=35
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_36]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=36
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_37]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=37
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_38]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=38
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_39]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=39
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_40]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=40
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_41]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=41
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_42]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=42
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_43]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=43
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_44]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=44
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_45]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=45
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_46]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=46
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_47]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=47
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_48]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=48
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_49]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=49
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_50]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=50
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_51]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=51
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_52]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=52
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_53]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=53
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_54]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=54
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_55]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=55
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_56]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=56
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_57]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=57
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_58]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=58
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_59]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=59
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_60]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=60
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_61]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=61
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_62]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=62
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_63]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=63
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_64]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=64
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_65]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=65
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_66]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=66
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_67]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=67
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_68]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=68
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_69]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=69
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_70]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=70
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_71]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=71
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_72]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=72
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_73]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=73
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_74]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=74
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_75]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=75
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_76]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=76
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_77]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=77
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_78]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=78
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_79]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=79
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_80]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=80
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_81]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=81
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_82]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=82
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_83]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=83
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_84]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=84
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_85]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=85
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_86]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=Sum
Type=Band
BandIdx=86
AverageSize=#AvgSoundLevel#

[MeasureFFT_L_87]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioRaw_Out
Channel=SUM
Type=Band
BandIdx=87
AverageSize=#AvgSoundLevel#

