; The current active colors for the skin

[Variables]
colorTitleBar=40,40,40
colorTitleBar2=20,20,20
colorSubtitleBar=64,64,64
colorSubtitleBar2=64,64,64
colorChannelBar=20,20,20
colorChannelBar2=20,20,20
colorChannelBarAlt=40,40,40
colorChannelBarAlt2=40,40,40
colorChannelBarHover=87,87,87
colorChannelBarHover2=0,0,0
colorBorder=128,128,128
colorProfileBorder=255,255,255
colorOnlineBorder=255,196,0
colorNumOnline=255,255,255
colorOnline=0,150,0
colorSubtitleText=255,255,255
colorStreamName=255,255,255
colorViewers=255,255,255
colorPlayingText=255,255,255
colorNotifName=255,255,255
colorGameName=209,175,40
colorComeOnline=0,200,0
